homeassistant:
  # Name of the location where Home Assistant is running
  name: Maison de Gano
  # Location required to calculate the time the sun rises and sets
  latitude: !secret halatitude
  longitude: !secret halongitude
  # C for Celcius, F for Fahrenheit
  #temperature_unit: C
 # unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Paris
  customize: !include devices/customize.yaml
  #whitelist_external_dirs:
  allowlist_external_dirs:
    - /config/www/surf

config:

mobile_app:

system_health:

recorder:
  purge_keep_days: 10

ssdp:
zeroconf:
wake_on_lan:

lovelace:
  # mode: yaml

bodymiscale: !include custom_components/bodymiscale/bodymiscale.yaml

fan:
  - platform: xiaomi_miio_fan
    name: Xiaomi Smart Fan
    host: 192.168.3.134
    token: !secret mifan
    model: dmaker.fan.p8


######### DEFINITION DES ZONES ###########
zone:
  name: Travail
  latitude: !secret travlatitude
  longitude: !secret travlongitude
  icon: mdi:castle
  radius: 500

zone 2:
  name: Maison de Gano
  latitude: !secret halatitude
  longitude: !secret halongitude
  icon: mdi:home
  radius: 500

zone 3:
  name: home
  latitude: !secret halatitude
  longitude: !secret halongitude
  radius: 100

cast:
  media_player:
  - host: 192.168.2.2
  - host: 192.168.10.7
  - host: 192.168.10.36
  - host: 192.168.10.4
  - host: 192.168.10.39
  - host: 192.168.10.42

frontend:
  # javascript_version: latest
  #themes:
  
  themes: !include_dir_merge_named themes

######### DEFINITION DES MOTEURS TTS ###########
tts:
  - platform: google_translate
    service_name: google_say
    language: 'fr'
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300

weather:
  - platform: darksky
    api_key: !secret darksky_api
    mode: daily
   

######### DEFINITION DES DETECTEURS DE MOUVEMENTS ###########
meteo_france:
  - city: 'Eysines'
  - city: 'Lacanau'

binary_sensor:
   - platform: mqtt
     name: trackroomami
     state_topic: "presence_nodes/trackroomami"
     json_attributes_topic: "presence_nodes/trackroomami/chambre3d"
     payload_on: "CONNECTED"
     payload_off: "DISCONNECTED"
     device_class: connectivity  

rfxtrx:
  device: /dev/serial/by-id/usb-RFXCOM_RFXtrx433_A1RTHG3-if00-port0
 # automatic_add: False
  automatic_add: True
  devices:
    091300479308f9019a70:
     # name: mvtsdb
     data_bits: 4
     command_on: 0x9
     command_off: 0x0
     device_class: motion
     fire_event: True
     off_delay:
       seconds: 5
    09130025ecad69019f80:
     # name: mvtwc
     data_bits: 4
     command_on: 0x9
     command_off: 0x0           
     device_class: motion
     fire_event: True
     off_delay:
       seconds: 5
    0a520d11df0100cc330179:
      # name: tempsdb
      # data_type:
      #  - Humidity
      #  - Temperature
    0a520d0d880100fe400179:
      # name: tempchambre
      # data_type:
      #  - Humidity
      #  - Temperature
    0a520d1bca0100d1360179:  
      # name: tempetage
      # data_type:
      #  - Humidity
      #  - Temperature


timer:
  timerwc:
    duration: '00:07:00'
  timersdb:
    duration: '00:10:00'
  timersdbnight:
    duration: '00:03:00'
  timercuisine:
    duration: '00:02:00'


######### DEFINITION DU PANNEAU D'ALARME ###########
alarm_control_panel:
  platform: manual
  code: !secret codeal

map:
  
######### DEFINITION DU BROKER MQTT LOCAL ###########
mqtt:
  broker: 192.168.3.8
  port: 1883
  keepalive: 60
  username: hadash
  password: !secret mqtt


input_text:
  text1:
    name: Text 1
    pattern: '[a-fA-F0-9]*'
  text2:
    name: Deezer link here
    pattern: '[a-fA-F0-9]*'

spotify:
  client_id: !secret spotifyclient
  client_secret: !secret spotifysecret

######### DEFINITION DES INPUT_SLIDER ###########

input_number:
  vacuumhour:
    name: Heure
    icon: mdi:timer
    initial: 9
    min: 0
    max: 23
    step: 1
    mode: slider
  vacuuminutes:
    name: Minutes
    icon: mdi:timer
    initial: 45
    min: 0
    max: 59
    step: 5
    mode: slider
  alarmhour:
    name: Heure
    icon: mdi:timer
    initial: 7
    min: 0
    max: 23
    step: 1
    mode: slider
  alarmminutes:
    name: Minutes
    icon: mdi:timer
    initial: 25
    min: 0
    max: 59
    step: 5
    mode: slider
  luminosite:
    name: Luminosité salon
    icon: mdi:light
    initial: 255
    min: 0
    max: 255
    step: 5
    mode: slider
  temperature:
    name: Temperature Maison
    icon: mdi:timer
    initial: 20
    min: 10
    max: 30
    step: 0.5
    mode: slider
  servo_control:
    name: Servo Control
    initial: 0
    min: -100
    max: 100
    step: 1
    mode: slider
  servo_control2:
    name: Servo Control Pan
    initial: 0
    min: -100
    max: 100
    step: 1
    mode: slider

 
 
######### DEFINITION DES INPUT_BOOLEAN ###########
input_boolean:
  vacuumauto:
    name: Mode Auto
    initial: off
  stopsoir:
    name: Eteint la lumiere la nuit
    initial: on
  autoprint2:
    name: Extinction auto A8
    initial: off
  autoprint:
    name: Extinction auto CR10
    initial: off
  squeeze:
    name: Squeeze PI Etat
    initial: off
  bonjour:
    name: Service bonjour
    initial: on
  bye:
    name: Service bye
    initial: on
  automa:
    name: Automatisation
    initial: on
  alarmweekday:
    name: Les jours de la semaine 
    initial: on
    icon: mdi:calendar
  alarmweekon:
    name: Activee     
    initial: on
  tvoffchambre:
    name: Allume le radiateur la nuit
    initial: off
  envoipic:
    name: Envoi video capturee
    initial: off
  cast_light:
    name: Chromecast lumieres
    initial: off
    icon: mdi:spotlight-beam
  freebox:
    name: Reveil Freebox
    initial: off
    icon: mdi:power
  rainbow_light:
    name: Effet Lumieres
    initial: off
    icon: mdi:traffic-light
  bieres:
    name: bieres
    initial: off
    icon: mdi:bitbucket
  papierwc:
    name: papier wc
    initial: off
    icon: mdi:emoticon-poop
  coca:
    name: coca
    initial: off
    icon: mdi:bitbucket
  lessive:
    name: lessive
    initial: off
    icon: mdi:car-wash
  poulet:
    name: poulet
    initial: off
    icon: mdi:paw
  steak:
    name: steak
    initial: off
    icon: mdi:paw
  poisson:
    name: poisson
    initial: off
    icon: mdi:fish
  shampooing:
    name: shampooing
    initial: off
    icon: mdi:car-wash
  geldouche:
    name: gel douche
    initial: off
    icon: mdi:car-wash
  cafe:
    name: cafe
    initial: off
    icon: mdi:coffee
  petitdej:
    name: a bouffer pour le matin
    initial: off
    icon: mdi:coffee
  cremefraiche:
    name: creme fraiche
    initial: off
    icon: mdi:bitbucket
  tomates:
    name: tomates
    initial: off
    icon: mdi:food-apple
  pommedeterre:
    name: pommes de terre
    initial: off
    icon: mdi:food
  poivron:
    name: poivrons
    initial: off
    icon: mdi:food-apple
  oignon:
    name: oignons
    initial: off
    icon: mdi:food-apple
  pizza:
    name: pizzas
    initial: off
    icon: mdi:pizza
  riz:
    name: Riz
    initial: off
    icon: mdi:food
  pates:
    name: pates
    initial: off
    icon: mdi:food-variant
  jambon:
    name: jambon
    initial: off
    icon: mdi:food
  apero:
    name: apero
    initial: off
    icon: mdi:food
  sacpoubelle:
    name: sacs poubelle
    initial: off
    icon: mdi:delete
  deo:
    name: déodorant
    initial: off
    icon: mdi:weather-windy
  dentifrice:
    name: dentifrice
    initial: off
    icon: mdi:brush
  oeufs:
    name: oeufs
    initial: off
    icon: mdi:food
  lait:
    name: lait
    initial: off
    icon: mdi:food
  trackme_arno:
    name: tracking arnaud
    initial: on


######### DEFINITION DES INPUT_SELECT ###########
input_select:
  themesi:
    name: 'Themes'
    options:
      - noir
      - rouge
      - vert
      - jaune
      - bleu
      - cyan
      - dark
      - white
    initial: noir
  categorie2:
    name: 'Type'
    options:
      - Choisir
      - divertissement
      - documentaires
      - films-telefilms
      - jeunesse
      - magazine
      - sport
    initial: Choisir
  radio_station:
    name: 'Radio Station:'
    options:
      - Franceinfo
      - Jazz
      - Nova Sauvagine
  chromecast_radio:
    name: 'Select Speakers:'
    options:
      - Google Home
      - Raspberry PI2
      - Shield
    initial: Google Home
    icon: mdi:speaker-wireless
  freeplayon:
    name: "Etat Allume Eteint Freebox"
    initial: "Off"
    options:
      - "On"
      - "Off"

######### DEFINITION DES COMMANDES SHELL POUR LA FREEBOX ###########
shell_command: !include shell_commands.yaml



######### DEFINITION DU COMPTE GOOGLE ###########
google:
  client_id: !secret googleclient_id
  client_secret: !secret googleclient_secret


google_assistant:
  project_id: arno-ac1da
  expose_by_default: false
  exposed_domains:
    - switch
    - light
    - media_player
    - script
    - scene
    - input_boolean
  entity_config:
    input_boolean.cast_light:
      name: mode cinema
      expose: true
      aliases:
        - mode cinema
    input_boolean.rainbow_light:
      name: mode soiree
      expose: true
      aliases:
        - mode soirée
    media_player.shield:
      name: nvidia shield
      expose: true
      aliases:
        - shield
        - nvidia shield
    script.surftv:
      name: Surf TV
      expose: true
      aliases:
        - webcam lacanau
        - webcam surf
    script.vacuumon:
      name: Vacuum On
      expose: true
      aliases:
        - l'aspirateur
    script.vacuumoff:
      name: Surf TV
      expose: true
      aliases:
        - retour à la base
        - arret aspirateur
    script.entreeVacuum:
      name: Vacuum Entree
      expose: true
      aliases:
        - l'aspirateur dans l'entree
    script.cuisineVacuum:
      name: Vacuum Cuisine
      expose: true
      aliases:
        - l'aspirateur dans la cuisine
    light.lumieres_du_salon:
      name: lumières salon
      expose: true
      aliases:
        - les lumières du salon
    light.bureau:
      name: lumières du bureau
      expose: true
      aliases:
        - la lumière du bureau
    light.cuisine:
      name: lumières de la cuisine
      expose: true
      aliases:
        - la lumière de la cuisine


######## #DEFINITION DES SENSORS ###########
sensor: !include devices/sensors.yaml

wemo:
  discovery: false  
  static:
    - 192.168.10.34



######### DEFINITION DES SWITCH WEMO ET DES DETECTEUR DE MVT RFX ###########
switch:
    - platform: broadlink
      mac: '34:EA:34:C9:A0:4D'
      switches:
        - name: 'Lampe Print'
        - name: 'Raspberry'
        - name: 'Creality CR10'
        - name: 'Anet A8'
    - platform: flux
      lights:
        - light.bibliocolor
        - light.bureau
        - light.escalier
        - light.hall
        - light.hue_lightstrip_1
        - light.hue_lightstrip_plus_1
        - light.salon_couleur
        - light.cuisine
        - light.wc
        - light.sdb
      name: Fluxer
      start_time: '7:00'
      stop_time: '23:00'
      start_colortemp: 4000
      sunset_colortemp: 3000
      stop_colortemp: 1900
      brightness: 250
      disable_brightness_adjust: true
      mode: xy
      transition: 30
      interval: 60       

vacuum:
    - platform: xiaomi_miio
      host: 192.168.3.45
      token: !secret vacuum
      name: Xiaomi vacuum

# Enables support for tracking state changes over time.
history:

# Track the sun
sun:

# Show links to resources in log and frontend

# View all events in a logbook
logbook:

logger:
  default: warn
  logs:
    # homeassistant.components.camera: fatal
    requests.packages.urllib3: critical
    urllib3.connectionpool: critical
    # homeassistant.components.switch: debug
    # homeassistant.components.broadlink: debug

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.0.3
    - 172.30.0.4 
    - 127.0.0.1
    - ::1

device_tracker: !include devices/tracker.yaml

# Discover some devices automatically
discovery:
  ignore:
    - yeelight

default_config:
  
# Allows you to issue voice commands from the frontend
conversation:

# Checks for available updates
updater:

telegram_bot:
  - platform: polling
    api_key: !secret teleapi_key
    allowed_chat_ids:
      - !secret telechat_id

######### DEFINITION DES SYSTEMES DE NOTIFICATION ###########
notify:
  - platform: telegram
    name: teleha
    api_key: !secret teleapi_key
    chat_id: !secret telechat_id

media_player: !include devices/media_players.yaml

######### DEFINITION DES LUMIERES ###########
hue:
  bridges:
    - host: 192.168.3.50
      allow_hue_groups: true
      allow_unreachable: true

light: !include devices/lights.yaml

yeelight:
  devices:
    192.168.3.101:
      name: chambrechevet
      model: bslamp1


######### DEFINITION DES CAMERAS / IMAGES ###########
camera:
  - platform: local_file
    file_path: /config/www/surf/videos/Alarme/deepstack_person_detector_latest.jpg
    name: deepstack_snapshot
  - platform: generic
    still_image_url: http://api.sat24.com/animated/EU/infraPolair/2/Romance%20Standard%20Time/628670
    #still_image_url: http://api.sat24.com/crop?type=visual5hdcomplete&lat=44.8378&lon=-0.5792&width=300&height=300&zoom=0.70&continent=eu
    name: infrarouge
  - platform: generic
    still_image_url: http://api.sat24.com/animated/EU/visual/2/Romance%20Standard%20Time/555674
    name: france
  - platform: local_file
    file_path: /config/www/surf/surf.png
    #file_path: /home/gano/.homeassistant/www/surf/surf.png
    name: surf
  - platform: local_file
    #file_path: /home/gano/.homeassistant/www/QR_CODE.png
    file_path: /config/www/QR_CODE.png
    name: qrcode
  - platform: generic
    still_image_url: http://192.168.3.8:8123/local/surf/surf.png
    # stream_source: http://192.168.3.8:8123/local/surf/surf.png
    #file_path: /home/gano/.homeassistant/www/surf/surf.png
    name: surf2
  - platform: generic
    still_image_url: http://192.168.3.8:3000/render/d-solo/CMkcxn8Zz/homeassistant?orgId=1&refresh=5m&kiosk=tv&panelId=4&width=1000&height=500&tz=Europe%2FParis
    name: grafanatempsdb
  - platform: generic
    still_image_url: http://192.168.3.8:3000/render/d-solo/CMkcxn8Zz/homeassistant?orgId=1&refresh=5m&kiosk=tv&panelId=6&width=1000&height=500&tz=Europe%2FParis
    name: grafanatempsalon
  - platform: generic
    still_image_url: http://192.168.3.8:3000/render/d-solo/CMkcxn8Zz/homeassistant?orgId=1&refresh=5m&kiosk=tv&panelId=2&width=1000&height=500&tz=Europe%2FParis
    name: grafanatempschambre
  - platform: generic
    still_image_url: http://192.168.3.8:3000/render/d-solo/CMkcxn8Zz/homeassistant?orgId=1&refresh=5m&kiosk=tv&panelId=8&width=1000&height=500&tz=Europe%2FParis'
    name: grafanatraefik
  - platform: generic
    still_image_url: http://192.168.3.8:3000/render/d-solo/CMkcxn8Zz/homeassistant?orgId=1&refresh=5m&kiosk=tv&panelId=16&width=1000&height=500&tz=Europe%2FParis'
    name: grafanaenedis     
  - platform: generic
    still_image_url: http://192.168.3.8:3000/render/d-solo/CMkcxn8Zz/homeassistant?orgId=1&refresh=5m&kiosk=tv&panelId=12&width=1000&height=500&tz=Europe%2FParis'
    name: grafanacpu     
  - platform: generic
    still_image_url: http://192.168.3.8:3000/render/d-solo/CMkcxn8Zz/homeassistant?orgId=1&refresh=5m&kiosk=tv&panelId=10&width=1000&height=500&tz=Europe%2FParis'
    name: grafanamem     
  - platform: generic
    still_image_url: http://192.168.3.8:3000/render/d-solo/CMkcxn8Zz/homeassistant?orgId=1&refresh=5m&kiosk=tv&panelId=14&width=1000&height=500&tz=Europe%2FParis'
    name: grafanadisk     
  - platform: mjpeg
    mjpeg_url: http://192.168.10.49:2971/camera/stream
    name: salon_webcam
#  - platform: zoneminder
  # - platform: mjpeg
  #   mjpeg_url: http://192.168.10.15:9902
  #   name: salon2
  - platform: ffmpeg
    input: /config/www/surf/videos/webcamsurf_nord.mp4
    #input: /home/gano/.homeassistant/www/surf/webcamsurf.mp4
    name: webcamsurfnord
  - platform: ffmpeg
    input: /config/www/surf/videos/webcamsurf_nord2.mp4
    #input: /home/gano/.homeassistant/www/surf/webcamsurf.mp4
    name: webcamsurfnord2
  - platform: ffmpeg
    input: /config/www/surf/videos/webcamsurf_centrale.mp4
    #input: /home/gano/.homeassistant/www/surf/webcamsurf.mp4
    name: webcamsurfcentrale
  - platform: mjpeg
    mjpeg_url: https://platforms5.joada.net/embeded/embeded.html?uuid=67eb6464-055f-47cb-3730-3330-6d61-63-abc5-fa5259757cc4d&type=live&liveicon=1&vsheader=1&tz=Europe/Paris&tsp=1594647886&titletext=
    #input: /home/gano/.homeassistant/www/surf/webcamsurf.mp4
    name: webcamsurflive
  - platform: mjpeg
    mjpeg_url: http://192.168.10.18:8080/?action=stream
    name: camcr10
    still_image_url: http://192.168.10.18:8080/?action=snapshot
  - platform: mjpeg
    mjpeg_url: http://192.168.10.5:8080/?action=stream
    name: cama8
    still_image_url: http://192.168.10.5:8080/?action=snapshot


######### DEFINITION DES GROUPES ###########
group: !include_dir_merge_named group


######### DEFINITION DES SCENES ###########
scene: !include scenes.yaml

######### DEFINITION DES AUTOMATISATIONS ###########
automation: !include automations.yaml

######### DEFINITION DES SCRIPTS ###########
script: !include scripts.yaml

