- platform: group
  name: lumieres du salon
  entities:
    - light.bibliocolor
    - light.bureau
    - light.hue_lightstrip_1
    - light.hue_lightstrip_plus_1
    - light.salon_couleur

- platform: hyperion
  host: 192.168.10.40
