# - platform: cast
#   host: 192.168.2.2
# - platform: cast
#   host: 192.168.10.7
# - platform: cast
#   host: 192.168.10.36
# - platform: cast
#   host: 192.168.10.4    
# - platform: cast
#   host: 192.168.10.13
- platform: panasonic_viera
  host: 192.168.10.44
  port: 55000
  mac: 24:EC:99:2C:D7:AC
  app_power: true
  turn_on_action:
    - service: wake_on_lan.send_magic_packet
      data:
        mac: "24:EC:99:2C:D7:AC"
  # name: Tele du salon
- platform: plex
- platform: androidtv
  name: Android TV Shield
  host: 192.168.10.41
  #adb_server_ip: 127.0.0.1
  #adb_server_port: 5037
  turn_on_command: "input keyevent 3"
  turn_off_command: "input keyevent 223"
  state_detection_rules:
    'com.amazon.tv.launcher':
      - 'standby'
    'com.netflix.ninja':
      - 'media_session_state'
    'com.ellation.vrv':
      - 'audio_state'
    'com.plexapp.android':
      - 'paused':
          'media_session_state': 2  # this indentation is important!
          #'wake_lock_size': 1       # this indentation is important!
      - 'playing':
          'media_session_state': 3  # this indentation is important!
      - 'standby'
    'com.amazon.avod':
      - 'playing':
          'wake_lock_size': 4  # this indentation is important!
      - 'playing':
          'wake_lock_size': 3  # this indentation is important!
      - 'paused':
          'wake_lock_size': 2  # this indentation is important!
      - 'paused':
          'wake_lock_size': 1  # this indentation is important!
      - 'standby'
  # host: 192.168.2.2
  # name: Ganoplex
# - platform: vlc
#   name: vlcpi
#   arguments: '--alsa-audio-device=hw:1,0'
# - platform: mpd
#   host: 192.168.10.15
# - platform: mpd
#   host: 192.168.10.12
# - platform: squeezebox
#   host: 192.168.10.21
#   port: 9002
# - platform: squeezebox
#   host: 192.168.10.15

