#- platform: wemo
#  scan_interval: 10


- platform: flux
  lights:
    - light.bibliocolor
    - light.bureau
    - light.escalier
    - light.hall
    - light.hue_lightstrip_1
    - light.hue_lightstrip_plus_1
    - light.salon_couleur
  name: Fluxer
  start_time: '7:00'
  stop_time: '23:00'
  start_colortemp: 4000
  sunset_colortemp: 3000
  stop_colortemp: 1900
  brightness: 200
  disable_brightness_adjust: true
  mode: xy
  transition: 30
  interval: 60
#- platform: zoneminder
#  command_on: Modect
#  command_off: Monitor
